@Products.API_HostAddress = http://localhost:5000


//In Products.API/Program.cs

builder.Services.AddHttpClient("PlatformSH", client =>
{
    // Api URL
    client.BaseAddress = new Uri("https://api.platform.sh/api/projects/pj2g557uk2z2g/");
});

